language: php

php:
  - 7.1
  - 7.2

dist: trusty

env:
  global:
    - DEFAULT=1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.9 && vendor/bin/phpstan analyse -c phpstan.neon -l 2 src; fi

notifications:
  email: false